version: '3'
services:
  prisma2:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "5000:5000"
    environment:
      PRISMA_CONFIG: |
        port: 5000
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: loon_ai
            schema: public
            user: loon
            password: loonlab505
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: false